package pl.alburnus.mybatis.generator.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import pl.alburnus.mybatis.generator.entity.Teammate;
import pl.alburnus.mybatis.generator.entity.TeammateExample;

public interface TeammateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    @SelectProvider(type=TeammateSqlProvider.class, method="countByExample")
    long countByExample(TeammateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TeammateSqlProvider.class, method="deleteByExample")
    int deleteByExample(TeammateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    @Delete({
        "delete from teammate",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    @Insert({
        "insert into teammate (name, team_id)",
        "values (#{name,jdbcType=VARCHAR}, #{teamId,jdbcType=BIGINT})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(Teammate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    @InsertProvider(type=TeammateSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(Teammate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    @SelectProvider(type=TeammateSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="team_id", property="teamId", jdbcType=JdbcType.BIGINT)
    })
    List<Teammate> selectByExample(TeammateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, team_id",
        "from teammate",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="team_id", property="teamId", jdbcType=JdbcType.BIGINT)
    })
    Teammate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TeammateSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Teammate record, @Param("example") TeammateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TeammateSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Teammate record, @Param("example") TeammateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TeammateSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Teammate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    @Update({
        "update teammate",
        "set name = #{name,jdbcType=VARCHAR},",
          "team_id = #{teamId,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Teammate record);
}