package pl.alburnus.mybatis.generator.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pl.alburnus.mybatis.generator.entity.TeamMate;
import pl.alburnus.mybatis.generator.entity.TeamMateExample;

public interface TeamMateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    long countByExample(TeamMateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    int deleteByExample(TeamMateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    int insert(TeamMate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    int insertSelective(TeamMate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    List<TeamMate> selectByExample(TeamMateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    TeamMate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TeamMate record, @Param("example") TeamMateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TeamMate record, @Param("example") TeamMateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TeamMate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeamMate record);
}